export const ADD_IMAGE = 'ADD_IMAGE';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const FETCH_TEMPLATES = 'FETCH_TEMPLATES';
export const APPLY_TEMPLATE = 'APPLY_TEMPLATE';
export const JUMP_TO_PAGE = 'JUMP_TO_PAGE';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const UPDATE_REGISTER_VALUE = "UPDATE_REGISTER_VALUE";
export const ADD_IMAGE_TO_FRAME = 'ADD_IMAGE_TO_FRAME';
export const ADD_TEXT_TO_PAGE = 'ADD_TEXT_TO_PAGE';
export const TOGGLE_PREVIEW = 'TOGGLE_PREVIEW';
export const NEXT_PAGE = 'NEXT_PAGE';
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE';
export const SEND_ORDER = "SEND_ORDER";
export const ADD_TEXT_TO_FRAME = 'ADD_TEXT_TO_FRAME';
// Navigation variables
export const REDIRECT_TO_LOGIN = "REDIRECT_TO_LOGIN";
export const REDIRECT_TO_REGISTRATION = "REDIRECT_TO_REGISTRATION";
export const REDIRECT_TO_HOME = "REDIRECT_TO_HOME";
export const REDIRECT_TO_EXPORT_PDF = "REDIRECT_TO_EXPORT_PDF";
export const REDIRECT_TO_PREVIEW = "REDIRECT_TO_PREVIEW";
export const REDIRECT_TO_ORDER_PAGE = "REDIRECT_TO_ORDER_PAGE";

