export const ADD_IMAGE = 'ADD_IMAGE';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const FETCH_TEMPLATES = 'FETCH_TEMPLATES';
export const APPLY_TEMPLATE = 'APPLY_TEMPLATE';
export const JUMP_TO_PAGE = 'JUMP_TO_PAGE';