export const ADD_IMAGE = 'ADD_IMAGE';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const FETCH_TEMPLATES = 'FETCH_TEMPLATES';
export const SELECT_TEMPLATE = 'SELECT_TEMPLATE';