import React, { Component } from 'react';
import RaisedButton from 'material-ui/RaisedButton';
import { closeTOSModal } from '../../actions/termsOfServiceActions';
import { connect } from 'react-redux';
import PropTypes from 'prop-types';
import '../../styles/TermsOfService.css';

class TermsOfService extends Component {

    render() {
      return(
        <div className="tos-modal-background">
          <div className="tos-modal-container">
            <div className="tos-modal-content">
              <h1>Terms of Service</h1>
              <div className="tos-modal-content-content">
                By using the Mini-Mag Maker, you agree to the following Terms of Use:<br/><br/>

                <b>Ownership of Uploaded Images</b><br/>
                The BCIT Student Association (BCITSA) agrees that you retain all legal rights to the images that you upload. You are responsible for your images, and you may edit or delete your images. BCITSA will use your images to manufacture photo products per your request. BCITSA will only use your images in promotional materials with your express permission.<br/><br/>

                <b>Inappropriate Images</b><br/>
                Images that you upload to the BCITSA Mini-Mag Maker must comply with the <a href="https://www.bcit.ca/files/pdf/policies/1500.pdf">British Columbia Institute of Technology (BCIT) Code of Conduct</a>. If you attempt to upload images that violate this Code of Conduct, or any other content that violates any applicable statute(s) including (but not limited to) images depicting: extreme violence, pornography, sexual violence, racism and other forms of prejudice, BCITSA reserves the right to delete these images that you upload, terminate your account and immediately report the activity to BCIT Safety &amp; Security, which may impact your academic standing as a BCIT student. Where applicable, BCITSA may also report violations to law enforcement agencies. For more information on BCIT’s Safety and Security policy, please review <a href="https://www.bcit.ca/files/pdf/policies/7100.pdf">Policy 7100</a><br/><br/>

                <b>Intellectual Property</b><br/>
                Images that you upload to the BCITSA Mini-Mag Maker must be: owned by you, and/or public domain, and/or licensed to you by the original owner. For more information about the Use of Material Protected by Copyright, please read BCIT <a href="https://www.bcit.ca/files/pdf/policies/7506.pdf">Policy 7506</a>.<br/><br/>

                <b>Ownership Of Designs Generated or Displayed By Software</b><br/>
                By using BCITSA's software to either generate or display designs for photo books, BCITSA is being granted ownership over the generated or displayed design. This does not refer to ownership of images, to which the uploader retains the legal right. Scenarios where designs are generated by software include but are not limited to layouts, use of property effects, stacking, arrangement, alignment, etc. Scenarios where a design is displayed by software include creating designs in third party programs but then uploading finished images to BCITSA.<br/><br/>

                <b>Termination of Account</b><br/>
                Uploading of inappropriate images and/or violations of other Terms of Use may lead to account termination.<br/><br/>

                <b>Product Discontinuation</b><br/>
                BCITSA reserves the right to cancel book projects in the event that a product is no longer offered.<br/><br/>

                <b>Third Party Composite Designs</b><br/>
                BCITSA software is unable to check the resolution quality of individual images used in composite designs generated in third party programs. If a collection of images are generated in a third party program such as Photoshop and then uploaded as a single .jpg composite spread, BCITSA software can only read the resolution quality of the entire flattened file. BCITSA therefore cannot be responsible for resolution quality of individual images composited together in third party programs.<br/><br/>

                <b>Debilitating Actions</b><br/>
                If an account engages in debilitating actions such as purposefully generating spam emails, threatening support agents, or placing a high volume of fraudulent design orders then a courteous warning will be issued. If warnings do not resolve the situation BCITSA reserves the right to suspend accounts.<br/><br/>

                <b>Limited Liability</b><br/>
                In no event will BCITSA be liable for any lost revenue, profit or data, or for special, indirect, consequential, incidental, or punitive damages however caused and regardless of the theory of liability arising out of the use of or inability to use BCITSA or arising out of any images posted on BCITSA even if BCITSA has been advised of the possibility of such damages.<br/><br/>

                <b>Changes to Terms &amp; Conditions</b><br/>
                These Terms &amp; Conditions may be changed by BCITSA with or without notice. Please review this page regularly for changes. Continued use of this web site following any change constitutes your acceptance of the change.<br/><br/>
              <RaisedButton
                primary={true}
                label="Close"
                onClick={this.props.closeTOSModal}
                className="tos-button"
              />
              </div>
          </div>
        </div>
      </div>
      );
    }
}

TermsOfService.propTypes = {
    closeTOSModal: PropTypes.func.isRequired,
    termsOfServiceIsOpen: PropTypes.bool,
};

const mapStateToProps = state => ({
    termsOfServiceIsOpen: state.user.termsOfServiceIsOpen,
});

export default connect(mapStateToProps, { closeTOSModal })(TermsOfService);